#!/usr/bin/env bash
# =============================================================================
# Iron-Gator Installer — Zero-Touch environment build
# Enforces 1.5B Chassis + 3,672-record Logic Gate on RTX 3050-class hardware.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV="$ROOT/venv"
BIN_DIR="$ROOT/bin"
LIB_SRC="$ROOT/src/inference/libgator_kern.so"
LIB_DST="/usr/local/lib/libgator_kern.so"
GATE_FILE="$BIN_DIR/logic_map.gate"
GATE_PREV="$BIN_DIR/logic_map.gate.prev"
GATOR_CTL_DST_DEFAULT="$HOME/.local/bin/GATOR_CTL"

VRAM_HARD_CAP_MIB="${GATOR_VRAM_HARD_CAP_MIB:-4096}"   # block donor below this
VRAM_GUARD_MIB="${GATOR_VRAM_GUARD_MIB:-2200}"         # bridge runtime guard
MIN_GATE_RECORDS="${GATOR_MIN_GATE_RECORDS:-3500}"
ASSUME_YES="${ASSUME_YES:-false}"

log()  { echo -e "[installer] $*"; }
fail() { echo -e "[installer][FATAL] $*" >&2; exit 1; }

for arg in "$@"; do
  case "$arg" in
    -y|--yes) ASSUME_YES="true" ;;
    *) fail "unknown arg: $arg" ;;
  esac
done

# -----------------------------------------------------------------------------
# 1. VRAM PROFILING — block 35B donor on low-VRAM hosts
# -----------------------------------------------------------------------------
log "Phase 1: VRAM profiling"
VRAM_TOTAL_MIB=0
if command -v nvidia-smi >/dev/null 2>&1; then
  VRAM_TOTAL_MIB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -n1 | tr -d ' ')
  log "  nvidia-smi reports ${VRAM_TOTAL_MIB} MiB total VRAM"
else
  log "  nvidia-smi unavailable — assuming CPU-only host"
fi

CHASSIS_LOCK="false"
if [[ "$VRAM_TOTAL_MIB" -lt "$VRAM_HARD_CAP_MIB" ]]; then
  CHASSIS_LOCK="true"
  log "  VRAM ${VRAM_TOTAL_MIB} MiB < ${VRAM_HARD_CAP_MIB} MiB hard-cap → 1.5B Chassis LOCKED"
  log "  Donor (>14 GB) will be blocked at runtime"
fi

# Persist guardrails so bridge + bootstrap honour them
mkdir -p "$ROOT/config"
cat > "$ROOT/config/iron_gator.env" <<EOF
# Generated by installer.sh — do not edit by hand
GATOR_CHASSIS_LOCK=${CHASSIS_LOCK}
GATOR_VRAM_HARD_CAP_MIB=${VRAM_HARD_CAP_MIB}
GATOR_VRAM_GUARD_MIB=${VRAM_GUARD_MIB}
GATOR_GRAFT_BIAS_SCALE=4.0
GATOR_REPEAT_PENALTY=1.18
GATOR_PRESENCE_PENALTY=0.4
GATOR_FREQUENCY_PENALTY=0.3
GATOR_DONOR_BLOCK=${CHASSIS_LOCK}
EOF
log "  guardrails written to config/iron_gator.env"

# -----------------------------------------------------------------------------
# 2. DEPENDENCY LOCKING — pin to the validated set
# -----------------------------------------------------------------------------
log "Phase 2: Dependency locking"
if [[ ! -d "$VENV" ]]; then
  python3 -m venv "$VENV"
  log "  created venv at $VENV"
fi
# shellcheck source=/dev/null
source "$VENV/bin/activate"
pip install --quiet --upgrade pip
pip install --quiet -r "$ROOT/requirements.txt"
log "  pinned deps installed (see requirements.txt)"

# -----------------------------------------------------------------------------
# 3. BINARY PLACEMENT — kernel .so + GATOR_CTL on PATH
# -----------------------------------------------------------------------------
log "Phase 3: Binary placement"
if [[ ! -f "$LIB_SRC" ]]; then
  log "  libgator_kern.so missing — invoking bootstrap.sh build path"
  bash "$ROOT/bootstrap.sh" --dry-run >/dev/null 2>&1 || true
  bash "$ROOT/bootstrap.sh" || fail "kernel build failed"
fi

if [[ -w /usr/local/lib ]] || [[ "$EUID" -eq 0 ]]; then
  install -m 0755 "$LIB_SRC" "$LIB_DST"
  log "  installed kernel → $LIB_DST"
else
  if [[ "$ASSUME_YES" == "true" ]]; then
    sudo install -m 0755 "$LIB_SRC" "$LIB_DST" || log "  WARN: sudo install failed; using in-tree path"
  else
    log "  /usr/local/lib not writable; bridge will use in-tree $LIB_SRC (use sudo or -y to install system-wide)"
  fi
fi
ldconfig 2>/dev/null || true

# GATOR_CTL — install to ~/.local/bin (always user-writable)
GATOR_CTL_SRC="$ROOT/tools/gator_ctl.py"
[[ -f "$GATOR_CTL_SRC" ]] || fail "tools/gator_ctl.py missing"
mkdir -p "$(dirname "$GATOR_CTL_DST_DEFAULT")"
cat > "$GATOR_CTL_DST_DEFAULT" <<EOF
#!/usr/bin/env bash
# Generated by installer.sh — Iron-Gator control tool
exec "$VENV/bin/python" "$GATOR_CTL_SRC" "\$@"
EOF
chmod +x "$GATOR_CTL_DST_DEFAULT"
log "  installed GATOR_CTL → $GATOR_CTL_DST_DEFAULT"
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) log "  HINT: add \$HOME/.local/bin to your PATH" ;;
esac

# -----------------------------------------------------------------------------
# 4. GATE HYGIENE — verify 3,500+ record graft is present
# -----------------------------------------------------------------------------
log "Phase 4: Gate hygiene"
NEED_EXTRACT="false"
if [[ ! -f "$GATE_FILE" ]]; then
  log "  logic_map.gate MISSING"
  NEED_EXTRACT="true"
else
  GATE_RECORDS=$("$VENV/bin/python" - <<PY
import gzip, pickle, sys
try:
    with gzip.open("$GATE_FILE", "rb") as fh:
        d = pickle.load(fh)
    print(len(d.get("records", [])))
except Exception as e:
    print(0)
PY
)
  log "  logic_map.gate has $GATE_RECORDS records (min ${MIN_GATE_RECORDS})"
  if [[ "$GATE_RECORDS" -lt "$MIN_GATE_RECORDS" ]]; then
    log "  gate DEGENERATE — re-extraction required"
    NEED_EXTRACT="true"
  fi
fi

if [[ "$NEED_EXTRACT" == "true" ]]; then
  if [[ "$CHASSIS_LOCK" == "true" ]]; then
    fail "Cannot run extraction on a chassis-locked host (donor needs >14 GB VRAM). Ship a pre-built logic_map.gate or run extraction on a higher-VRAM machine and copy the gate file into bin/."
  fi
  log "  triggering run_extraction.sh — this is a multi-hour job"
  if [[ "$ASSUME_YES" != "true" ]]; then
    read -r -p "  Proceed with extraction? [y/N] " ans
    [[ "$ans" =~ ^[Yy]$ ]] || fail "user aborted; place a valid logic_map.gate in bin/ and re-run"
  fi
  bash "$ROOT/run_extraction.sh"
fi

# Snapshot a fresh .prev fallback if missing
if [[ -f "$GATE_FILE" && ! -f "$GATE_PREV" ]]; then
  cp "$GATE_FILE" "$GATE_PREV"
  log "  snapshotted $GATE_PREV (auto-revert fallback)"
fi

# -----------------------------------------------------------------------------
log ""
log "============================================================="
log " Iron-Gator install complete."
log "   chassis-lock      : $CHASSIS_LOCK"
log "   VRAM hard-cap     : ${VRAM_HARD_CAP_MIB} MiB"
log "   VRAM runtime guard: ${VRAM_GUARD_MIB} MiB"
log "   gate records      : ${GATE_RECORDS:-?}"
log " Next: python3 bootstrap.py     (4-phase Brain-Start)"
log "============================================================="
