"""Calibration prompt corpus for Project Gator deep extraction.

Three domains, ~85 prompts each, target ≥250 prompts. Each prompt is fed to
the donor (35B) on its own; the donor generates ~22 tokens of reasoning;
each generated token contributes one record (top-64 logprobs) to the gate.
Target: ~5,500 records.

Categories (the `c` field in each record):
    1 = Technical Triage     (HTTP/API/network/system errors)
    2 = Project Context      (Maya, Iron-Gator, Gator architecture)
    3 = Agentic Reasoning    (dream cycles, planning, autonomous decisions)
"""

# ---------------------------------------------------------------------------
# Category 1: Technical Triage
# ---------------------------------------------------------------------------
TECHNICAL_TRIAGE = [
    "When a 502 Bad Gateway is returned, the upstream server most likely",
    "A 502 from nginx in front of a python uvicorn app usually means",
    "ECONNREFUSED with errno 111 against a localhost port indicates that",
    "ETIMEDOUT errno 110 differs from ECONNREFUSED because",
    "EPIPE errno 32 happens when a process writes to",
    "A 504 Gateway Timeout differs from 502 because the gateway",
    "HTTP 503 Service Unavailable is typically returned when",
    "HTTP 429 Too Many Requests should be handled by the client with",
    "A 404 Not Found from a REST API on an existing route suggests",
    "A 401 Unauthorized differs from 403 Forbidden because 401 means",
    "When a TCP connection RSTs immediately, the kernel side is",
    "A SYN-SENT socket stuck for 60 seconds likely indicates",
    "DNS resolution failures during HTTP calls show up in python as",
    "A SIGPIPE during a write to a closed socket is converted to",
    "When journalctl shows OOM-killer fired on a python process, the cause is",
    "A python process with VmSwap > 0 means the kernel paged out",
    "ulimit -n exceeded shows up at the syscall level as",
    "Disk full (ENOSPC errno 28) during a log write causes the writer to",
    "A llama.cpp /v1/completions returning 500 with 'CUDA out of memory'",
    "When nvidia-smi shows 100% GPU util but no progress, the model is",
    "If curl --max-time 30 exits with code 28, the meaning is",
    "An nginx config reload after a syntax error leaves the server running",
    "A systemd unit in 'activating (auto-restart)' state means",
    "A python ImportError at startup of a uvicorn app causes uvicorn to",
    "When pip install fails with 'No space left on device', the cache is",
    "A FastAPI endpoint hanging forever usually has a missing await on",
    "JSONDecodeError on a streaming SSE response usually means",
    "A websocket closing with code 1006 indicates abnormal closure caused by",
    "When a shell script fails with set -e and exits silently, you debug by",
    "A bash heredoc terminated by EOF at column 0 is required because",
    "When wsl --shutdown is run, all distributions are",
    "A linux cgroup OOM in WSL2 manifests as the entire VM",
    "If /proc/sys/vm/overcommit_memory is 2, malloc returning NULL means",
    "An mmap returning MAP_FAILED with ENOMEM indicates",
    "When llama-server prints 'failed to load model', the most common cause is",
    "A CUDA error 700 (illegal memory access) inside llama.cpp usually means",
    "When ggml prints 'no kernel found for op' the model uses an op",
    "A symbol-not-found error loading a .so via ctypes is fixed by",
    "When ldd shows 'not found' for a shared library, the loader cannot",
    "An nvidia-smi command returning 'No devices were found' inside WSL means",
    "A 502 returned by a reverse proxy in front of a slow LLM is fixed by",
    "Setting proxy_read_timeout in nginx affects the duration the proxy will",
    "An HTTP/1.1 keepalive connection closed by the server mid-request causes",
    "When a process is stuck in D state (uninterruptible sleep) the cause is",
    "A python asyncio task that never awaits will appear in logs as",
    "If uvicorn workers respawn every few seconds, the cause is usually",
    "The difference between SIGTERM and SIGKILL on a python process is",
    "A python process holding a file handle that was deleted shows in lsof as",
    "When two python processes both bind port 8080, the second one gets",
    "An LLM streaming endpoint that buffers responses delays the first token because",
    "A llama-server running with --n-gpu-layers 999 on a 6GB GPU will",
    "When VRAM is overcommitted, the kernel response in CUDA is to",
    "A stalled HTTP request that returns no headers means TCP is",
    "When a docker container exits with code 137, it was",
    "If iptables -L shows DROP on the loopback interface, localhost calls will",
    "A SystemD socket-activated service stays inactive until",
    "When the load average exceeds CPU count by 10x, the system is",
    "An NVMe drive throttled by thermal limit shows reduced throughput in",
    "A page fault that touches swap forces the process to wait on",
    "When fork() returns -1 with EAGAIN, the system has hit",
    "A poetry install failing with 'too many open files' is fixed by",
    "When curl -v shows TLS handshake stalling at 'Server hello', the cause is",
    "A CORS preflight failing with 'No Access-Control-Allow-Origin' means",
    "When a cron job runs but produces no output, stdout is",
    "If ssh into WSL2 hangs after auth, the cause is usually",
    "A git push rejected with 'pre-receive hook declined' means",
    "When pytest collects 0 tests, the conftest.py is probably",
    "A python segfault triggered by a C extension is debugged with",
    "When a python heap grows unbounded, the leak is usually in",
    "A 'Connection reset by peer' during a long upload indicates",
    "If openssl shows 'unable to verify the first certificate', the chain is",
    "When systemd-resolved is failing, /etc/resolv.conf points to",
    "A python multiprocessing pool deadlock is usually caused by",
    "When stdin is closed unexpectedly in a pipeline, the reader gets",
    "A deadlocked SQL transaction in postgres is broken by",
    "If a websocket sends a ping but no pong arrives within timeout, it",
    "When llama.cpp KV cache exhausts, generation will",
]

# ---------------------------------------------------------------------------
# Category 2: Project Context
# ---------------------------------------------------------------------------
PROJECT_CONTEXT = [
    "Maya is the operator of Project Gator, and she prefers responses that are",
    "Project Gator's architecture is a single-engine 1.5B chassis grafted with",
    "The chassis model is Qwen2.5-1.5B-Instruct in Q4_K_M quantization which",
    "The donor model was a 32B parameter Qwen2.5 in Q3 quantization, used only for",
    "Iron-Gator is the codename for the production deployment of Gator on",
    "The bridge process at port 8090 mediates between the user and the",
    "logic_map.gate is a gzipped pickle of records produced by distilling the",
    "libgator_kern.so is a native ctypes-loaded runtime that provides",
    "The Scratchpad component holds intermediate reasoning that the chassis can",
    "When Maya opens a chat session, the bridge maintains a chat memory of",
    "The dream-cycle is a maintenance routine that periodically",
    "The wakeup script launches event_bus, then gator-server, then bridge, then",
    "Gator's PersonaEngine ensures consistent voice across turns by injecting",
    "The PersistentContext tracker captures user-declared facts like names and",
    "The native gator-server is the llama.cpp server binary recompiled with",
    "Maya runs Gator on an RTX 3050 with 6 GB of VRAM, which constrains",
    "The decision to decommission the 32B donor was based on VRAM constraints and",
    "Logit-bias steering replaces the donor at runtime by reshaping",
    "The GATOR_GRAFT_BIAS_SCALE environment variable controls how aggressively",
    "When Maya says 'remember this', the bridge writes the fact into",
    "The Hive subsystem is responsible for distributing tasks across",
    "Telegram-Hive is the gateway that lets Maya talk to Gator from her phone via",
    "The command-center service exposes operational diagnostics on port",
    "The webui at port 8080 provides a chat interface with vital signs and",
    "Project Gator's identity statement begins with 'I am Gator, a single-engine",
    "Maintenance routines include log rotation, gate reload, and",
    "The agentic_cron service triggers periodic background tasks like",
    "The hybrid_memory module combines short-term chat with long-term",
    "Iron-Gator's success criteria require that the 1.5B can correctly triage",
    "The Maya Memory Test verifies cross-turn name recall and 502 triage in",
    "The /generate endpoint returns text plus telemetry such as",
    "The Scratchpad pipeline trace ['35B_Logic', 'Scratchpad_Write', '1.5B_Speech_Success'] means",
    "Project Gator was created to give Maya an autonomous AI companion that",
    "The launcher script checks three preflight conditions: chassis exists, gate exists,",
    "When the bridge starts, it loads logic_map.gate and prints a record count of",
    "The TTFT target on the 1.5B chassis is under 100 milliseconds because",
    "The VRAM budget for the live chassis is under 2.5 GB, leaving headroom for",
    "Maya's primary interface is the WebUI which she accesses at",
    "Gator's persona is calm, technical, slightly affectionate toward Maya, and never",
    "When asked about its origins, Gator should tell Maya that it was",
    "The event_bus is a pub-sub layer that decouples the bridge from",
    "Gator's response to a user it does not recognise is to",
    "Iron-Gator's deployment hardware is a stripped-down Windows host running",
    "The decommissioned donor lives at models/_decommissioned/donor.gguf.bak so that",
    "The chassis context window is 4096 tokens, which limits the conversation history to",
    "The persona_engine prepends a system prompt that begins with",
    "When the bridge cannot reach the gator-server, it returns to the user a",
    "The maintenance routine includes a daily call to session_reset which",
    "Project Gator's design philosophy is small-and-grafted rather than large-and-raw because",
    "The native kernel exposes gator_kern_logic_singleton_addr which the bridge",
    "Maya has explicitly asked that responses be free of emoji unless",
    "The codebase uses Python 3.11 in a venv at Gator/venv with dependencies",
    "Pickle-gzip was chosen for the gate format because it is small, fast, and",
    "The c field of a gate record is the category id and identifies which",
    "The t field of a gate record is a list of token ids, and the p field is",
    "When Maya types a question, the bridge first invokes the persona_engine, then",
    "The Iron-Gator production milestone requires that all six core services boot in under",
    "Gator's logs live in Gator/logs/ with one file per service such as",
    "The bridge's chat_memory is a deque with maxlen so that older turns",
    "Maya prefers honest answers over confident guesses, so when uncertain Gator should",
    "Project Gator's strict prohibition on hallucinated fact lookups is enforced by",
    "The dream_engine.py module runs while the user is idle and performs",
    "When the user says 'sleep' to Gator, the bridge schedules a dream cycle that",
    "The hive_state.json file tracks which hive nodes are healthy by",
    "The genesis_verify script is run after a fresh install to confirm",
    "An agentic_cron entry that has not fired in 24h indicates the cron loop is",
    "The pulse_check service emits heartbeat events every N seconds to confirm",
    "Maya works on the project from a Windows host using WSL2 Ubuntu, accessing files via",
    "The decision to forbid the chassis from making external HTTP calls is enforced by",
    "Gator should never claim to have run code that it has not verified by",
    "When asked who built Gator, the chassis should attribute it to Maya and",
    "The discovery module finds local services by scanning loopback ports in the range",
    "The Iron-Gator branding refers to the production-hardened aspect of Gator that",
    "Project Gator's origin story includes the abandonment of a much larger 35B model in favour of",
    "When the gate is reloaded mid-session, the bridge must call install_logit_bias to",
    "The Scholar_sense module assesses the difficulty of a user question by",
    "Maya's preferred greeting from Gator is succinct, technical, and",
    "Telegram messages received by Gator pass through telegram_gateway.py which",
]

# ---------------------------------------------------------------------------
# Category 3: Agentic Reasoning
# ---------------------------------------------------------------------------
AGENTIC_REASONING = [
    "When deciding whether to run a Dream Cycle, an agent should evaluate",
    "A long-running autonomous task should be decomposed into subgoals when",
    "Before taking a destructive action, an agent must obtain confirmation if",
    "The chain of reasoning for a tool call begins with stating the goal, then",
    "When two tools could accomplish the same goal, prefer the one that is",
    "An agent that detects an inconsistency between two facts should",
    "If an autonomous loop has run for N iterations without progress, the agent should",
    "When a user request is ambiguous, the most useful first action is to",
    "An agent should refuse to continue a task when it determines that continuing would",
    "Memory consolidation during a dream cycle prioritises facts that are",
    "When the agent encounters a new error class never seen before, it should",
    "The decision to escalate a task to a human is justified when",
    "An agent that has limited context budget should compress old turns by",
    "Before executing a shell command, an agent verifies it by checking",
    "When parallel tool calls share no data dependency, the agent should",
    "A planner that produces too many subtasks should re-evaluate its decomposition by",
    "When two subgoals conflict, the agent resolves the conflict by",
    "An agent observing that a service is unhealthy should first attempt",
    "The reasoning trace produced for an autonomous action should always include",
    "When a tool returns an error, the agent should classify the error as",
    "An agent that finds itself in a tight retry loop should add",
    "The decision to write a fact to long-term memory requires",
    "When asked to summarise a long conversation, the agent should preserve",
    "An autonomous task that depends on external network calls must implement",
    "Before claiming a task is complete, the agent verifies the outcome by",
    "When an agent detects that its own output may be wrong, it should",
    "A self-improvement cycle includes evaluating recent decisions and",
    "When state is shared across agents, conflict resolution requires",
    "An agent designed for low-resource hardware should prefer algorithms that",
    "The choice between greedy and beam search depends on whether the task is",
    "A context window of 4096 tokens forces the agent to summarise turns once",
    "When the agent must wait on a long-running process, the proper pattern is",
    "An agent that cannot reach its primary tool should fall back to",
    "Decomposing a debugging task starts with reproducing the failure, then",
    "When an agent loses confidence in its plan, the recovery is to",
    "Critical tasks should be checkpointed so that on restart the agent can",
    "An agent receiving conflicting instructions from two principals should",
    "When evaluating a hypothesis, the agent should first design a falsification",
    "The cost of running a sub-agent is justified when the task is",
    "An agent maintaining a todo list should mark items in progress when",
    "When the agent has spare cycles, the dream engine should review",
    "An autonomous test runner should treat a flaky test by",
    "When a deadline is approaching and the agent has not finished, it should",
    "Risk assessment for an autonomous action multiplies impact by",
    "An agent that delegates to a subagent must specify the return contract by",
    "When the agent discovers a new capability mid-task, it should",
    "A reasoning loop that produces the same answer twice should be terminated because",
    "Deciding whether to rebuild from scratch versus patch in place depends on",
    "An agent observing a new pattern across multiple tasks should write a",
    "When asked a yes-or-no question, the agent should answer with",
    "The agent's confidence in a fact should be tracked separately from",
    "When two memory entries conflict, the more recent one should",
    "An idle agent during a dream cycle should perform memory pruning of",
    "When the agent's plan requires user input, it should pause and ask rather than",
    "A successful autonomous loop terminates when the goal predicate evaluates to",
    "The agent should report progress to the user every N steps if N exceeds",
    "When an agent's tool call exceeds the timeout, the recovery is to",
    "Decomposition of a 'fix the bug' request begins by collecting",
    "An agent that completes a task must update any related state in",
    "When the user contradicts the agent, the agent should treat the user as",
    "Self-reflection at the end of a task should produce a brief lesson stored in",
    "The right level of verbosity for an agent's response depends on",
    "When the agent detects a security risk in a planned action, it must",
    "Logging decisions enables post-hoc audit, so every autonomous action should",
    "When an agent has multiple valid next actions, it should pick the one with",
    "Before deleting a file, an agent should verify that no other process",
    "The agent's authority to act is bounded by the user's stated permissions and",
    "When time pressure forces a shortcut, the agent should record the trade-off in",
    "A dream cycle that detects orphaned facts should reattach them to",
    "When the agent encounters a paradox in its memory, the recovery is to",
    "An agent operating without supervision must constrain itself by",
    "The frequency of dream cycles depends on the rate of new information arriving and",
    "When the agent's reasoning depends on a deprecated assumption, it must",
    "Autonomous learning should stop when the marginal benefit drops below",
    "When a long task is interrupted, the agent on resume should first",
    "The decision to emit a heartbeat depends on how long since the last",
    "An agent that observes its own loop running too fast should",
    "When processing a queue of tasks, priority should be assigned by",
    "Before publishing a result, the agent should self-review by checking",
    "An agent that has exhausted its plan should generate a new plan starting from",
    "Dream-cycle reflections are stored compactly so that future agents can",
]

ALL_PROMPTS = (
    [(1, p) for p in TECHNICAL_TRIAGE]
    + [(2, p) for p in PROJECT_CONTEXT]
    + [(3, p) for p in AGENTIC_REASONING]
)

if __name__ == "__main__":
    counts = {}
    for c, _ in ALL_PROMPTS:
        counts[c] = counts.get(c, 0) + 1
    print("Total prompts:", len(ALL_PROMPTS))
    for c, n in sorted(counts.items()):
        label = {1: "Technical Triage", 2: "Project Context", 3: "Agentic Reasoning"}[c]
        print(f"  cat {c} ({label}): {n}")
